language: node_js
node_js: "0.12"
script: npm run travisci
after_script:
  - codeclimate-test-reporter < coverage/combined/lcov.info
addons:
  code_climate:
    repo_token:
      secure: "HaMqEZBnnPREoQZwmW/XkiPCiy6G+4kXfSdhYKqxLjZuB/ak4ieA/+CptwkoUccpAXmgsm0/jbvTC+synJtfUM+58hH5VT7HnuM9jGVZoY2EjRalxLnI9doMJFjpdCrqUrQDUP3+QDZzkHPRIEv9KRe4nXuYAR0DjAISyGXM/vYLYpnQKKEqTbMP58GQVNFIG0kHlHtMTioATC6hQJoSpTvb2ZPLZRSYcC8ROapHz/iEWTtReXjnk/46ApXRjwxFiYKVzvMP+8lKsGoAIid5m7UEkpx6EdZTh5TIY0Hd1+RGTHhHRwS3QobOKAoN5pSM313dLQk3GoWHnN8oZRCrQ3zZ7IQU2r+JfbF0SuL8qhrX8aRDn2uGNJ1vdRY4Iv12OmfsTR4JG91jhTUedVgWkeYTIgjYvj4ygPJLNjTPaatAbFLb17269cXUStLFaLG/pwx4JqEwZULvhxySp4Ss5uSFFt8SwEDoF4kCDlGOsObYC7Zq/uhOy3slgz3XXU6Pp/Oqsx7/stJO9GkpqqwTYS2fEWCOPsCzMyjgS52dYS4AqeWOFu9XHsE0mBbZIak/xEmXlEv/mo8VeI33uUa5v1W3/n2yLpt9mBaUTwl45DU8MpS9Gpxm2Y8P29rG1pd8E2bUflql0tt7rEGvjqkZQUO2AY+xve4Q+GTAW/7+zY8="
